### ISSUE TITLE
java.lang.NullPointerException while set skin

### ISSUE THREAD

**Issue by Miriam0** [SergiFerry/PlayerNPC#18]
[17:04:54 ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.scores.ScoreboardTeam.g()" because "team" is null
        at net.minecraft.world.scores.Scoreboard.addPlayerToTeam(Scoreboard.java:214) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.ServerScoreboard.addPlayerToTeam(ServerScoreboard.java:91) ~[?:?]
        at puregero.multipaper.externalserverprotocol.ScoreboardUpdatePacket.handle(ScoreboardUpdatePacket.java:112) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at puregero.multipaper.externalserverprotocol.ScoreboardUpdatePacket.lambda$handle$0(ScoreboardUpdatePacket.java:86) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1372) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1349) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1342) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1320) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Miriam0** [comment]
someone?
