### ISSUE TITLE
Cannot set coordinates exactly to middle of block

### ISSUE THREAD

**Issue by tomikcz987** [SergiFerry/PlayerNPC#27]
Example command: /npcglobal action <npc> add both player_teleport_to_location <worldname> -2.5 57 17.5

```null
org.bukkit.command.CommandException: Unhandled exception executing command 'npcglobal' in plugin PlayerNPC v2023.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:975) ~[?:git-Purpur-1900]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[?:git-Purpur-1900]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[?:?]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:321) ~[?:git-Purpur-1900]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:305) ~[?:git-Purpur-1900]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2379) ~[?:git-Purpur-1900]
        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2339) ~[?:git-Purpur-1900]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59) ~[?:git-Purpur-1900]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:git-Purpur-1900]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153) ~[?:git-Purpur-1900]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24) ~[?:git-Purpur-1900]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1368) ~[?:git-Purpur-1900]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[?:git-Purpur-1900]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126) ~[?:git-Purpur-1900]
        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1345) ~[?:git-Purpur-1900]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1338) ~[?:git-Purpur-1900]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136) ~[?:git-Purpur-1900]
        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1316) ~[?:git-Purpur-1900]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1204) ~[?:git-Purpur-1900]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[?:git-Purpur-1900]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "-2.5"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:999) ~[?:?]
        at dev.sergiferry.playernpc.command.NPCGlobalCommand.lambda$static$128(NPCGlobalCommand.java:1856) ~[?:?]
        at dev.sergiferry.playernpc.command.NPCGlobalCommand.onExecute(NPCGlobalCommand.java:2507) ~[?:?]
        at dev.sergiferry.spigot.commands.CommandInstance.onCommand(CommandInstance.java:31) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[?:?]
        ... 23 more```

**Comment by SergiFerry** [comment]
Try with this, replace (id) and (world). In the latest version it only
works with number with no decimals, but in the future version it will work
with decimals.

/npcglobal action (id) add both player_teleport_to_location (world) -2 57 17

Thanks for reporting it
