### ISSUE TITLE
[11:52:17] [Server thread/WARN]: java.lang.IllegalArgumentException: Error at NMSEntityPlayer | I am using newest Version

### ISSUE THREAD

**Issue by Fusssl** [SergiFerry/PlayerNPC#33]
[11:52:17] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[11:52:17] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.create(NPC.java:817)
[11:52:17] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.reCreate(NPC.java:993)
[11:52:17] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.forceUpdate(NPC.java:852)
[11:52:17] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.forceUpdate(NPC.java:1593)
[11:52:17] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.lambda$forceUpdate$10(NPC.java:1975)
[11:52:17] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.forEachActivePlayer(NPC.java:1521)
[11:52:17] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.forceUpdate(NPC.java:1975)
[11:52:17] [Server thread/WARN]: 	at school.school.startCommand.onCommand(startCommand.java:53)
[11:52:17] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:52:17] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[11:52:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833)
[11:52:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[11:52:17] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:298)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1949)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1914)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:68)
[11:52:17] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017)
[11:52:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293)
[11:52:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:52:17] [Server thread/INFO]: java.lang.IllegalArgumentException: Error at NMSEntityPlayer

**Comment by SergiFerry** [comment]
Which is your server version? Which kind of server are you using? Spigot,
Paper...? Are you using BungeeCord?

Give me more details about when this error happens

**Comment by Fusssl** [comment]
I am using Spigot 1.19.2 from Gportal Host, no BungeeCord, it happens when i run a command which spawns npcs

**Comment by SergiFerry** [comment]
Can you send me the code at  startCommand.java:53 ?

**Comment by Fusssl** [comment]
[school.zip](https://github.com/SergiFerry/PlayerNPC/files/11159233/school.zip)
this is my plugin, need to go now if you need more info i am back in 4 hours

**Comment by Fusssl** [comment]
and did you notice anything?

**Comment by SergiFerry** [comment]
try by not force updating just at the beginning

**Comment by Fusssl** [comment]
without it, it doesnt change the skin etc. I see that the npcs spawns but with no name and no skin

**Comment by SergiFerry** [comment]
try only with npc.update()

**Comment by Fusssl** [comment]
i tried it makes the npc vanish, but i can still teleport to it with the command from the plugin

**Comment by SergiFerry** [comment]
ok, try by setting at PlayerNPC config, debug mode as true, and then doing
the forceUpdate(), and send me the log of the error

**Comment by Fusssl** [comment]
[20:08:44] [Server thread/INFO]: Fussl issued server command: /startnpcs
[20:08:44] [Server thread/INFO]: PlayerNPC | Registered School plugin into the NPCLib
[20:08:44] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[20:08:44] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedConstructorAccessor76.newInstance(Unknown Source)
[20:08:44] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:08:44] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:08:44] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.nms.minecraft.NMSEntityPlayer.newEntityPlayer(NMSEntityPlayer.java:49)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.create(NPC.java:815)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.reCreate(NPC.java:993)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.forceUpdate(NPC.java:852)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.forceUpdate(NPC.java:1593)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.lambda$forceUpdate$10(NPC.java:1975)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.forEachActivePlayer(NPC.java:1521)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.forceUpdate(NPC.java:1975)
[20:08:44] [Server thread/WARN]: 	at school.school.DirektorNpc.<init>(DirektorNpc.java:63)
[20:08:44] [Server thread/WARN]: 	at school.school.startCommand.onCommand(startCommand.java:39)
[20:08:44] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:08:44] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[20:08:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833)
[20:08:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[20:08:44] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:298)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1949)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1914)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:68)
[20:08:44] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293)
[20:08:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:08:44] [Server thread/WARN]: Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: ./Schule/stats/§8[NPC] 4768d.json
[20:08:44] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:121)
[20:08:44] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:68)
[20:08:44] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
[20:08:44] [Server thread/WARN]: 	at java.base/java.io.File.toPath(File.java:2387)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.getPlayerStats(PlayerList.java:1238)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.getPlayerStats(PlayerList.java:1224)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.<init>(EntityPlayer.java:307)
[20:08:44] [Server thread/WARN]: 	... 38 more
[20:08:44] [Server thread/WARN]: java.lang.IllegalArgumentException: Error at NMSEntityPlayer
[20:08:44] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.create(NPC.java:817)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.reCreate(NPC.java:993)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.forceUpdate(NPC.java:852)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.forceUpdate(NPC.java:1593)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.lambda$forceUpdate$10(NPC.java:1975)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.forEachActivePlayer(NPC.java:1521)
[20:08:44] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Global.forceUpdate(NPC.java:1975)
[20:08:44] [Server thread/WARN]: 	at school.school.DirektorNpc.<init>(DirektorNpc.java:63)
[20:08:44] [Server thread/WARN]: 	at school.school.startCommand.onCommand(startCommand.java:39)
[20:08:44] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:08:44] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[20:08:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833)
[20:08:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[20:08:44] [Server thread/WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:298)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1949)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1914)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:68)
[20:08:44] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017)
[20:08:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293)
[20:08:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:08:44] [Server thread/INFO]: java.lang.IllegalArgumentException: Error at NMSEntityPlayer
[20:08:45] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[20:08:45] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedConstructorAccessor50.newInstance(Unknown Source)
[20:08:45] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:08:45] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:08:45] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:08:45] [Server thread/WARN]: 	at dev.sergiferry.playernpc.nms.minecraft.NMSPacketPlayOutPlayerInfo.addPlayer(NMSPacketPlayOutPlayerInfo.java:56)
[20:08:45] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.addTabList(NPC.java:1118)
[20:08:45] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.showToClient(NPC.java:1282)
[20:08:45] [Server thread/WARN]: 	at dev.sergiferry.playernpc.api.NPC$Personal.lambda$show$0(NPC.java:915)
[20:08:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[20:08:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[20:08:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245)
[20:08:45] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394)
[20:08:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197)
[20:08:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013)
[20:08:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293)
[20:08:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:08:45] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.EntityPlayer.fz()" because "var0" is null
[20:08:45] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayOutPlayerInfo.a(SourceFile:45)
[20:08:45] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayOutPlayerInfo.<init>(SourceFile:26)
[20:08:45] [Server thread/WARN]: 	... 16 more
[20:08:45] [Server thread/WARN]: [School] Task #159 for School v1.0-SNAPSHOT generated an exception
java.lang.IllegalArgumentException: Cannot get GameProfile because NPC is not created yet.
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
	at dev.sergiferry.playernpc.api.NPC$Personal.getGameProfile(NPC.java:1337) ~[?:?]
	at dev.sergiferry.playernpc.api.NPC$Personal.updateTabList(NPC.java:1111) ~[?:?]
	at dev.sergiferry.playernpc.api.NPC$Personal.addTabList(NPC.java:1121) ~[?:?]
	at dev.sergiferry.playernpc.api.NPC$Personal.showToClient(NPC.java:1282) ~[?:?]
	at dev.sergiferry.playernpc.api.NPC$Personal.lambda$show$0(NPC.java:915) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3605-Spigot-6198b5a-f43634a]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3605-Spigot-6198b5a-f43634a]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3605-Spigot-6198b5a-f43634a]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3605-Spigot-6198b5a-f43634a]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3605-Spigot-6198b5a-f43634a]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3605-Spigot-6198b5a-f43634a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3605-Spigot-6198b5a-f43634a]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by SergiFerry** [comment]
Add me discord SergiFerry#5185 , and I will send you a beta version of
PlayerNPC that tries to fix this error.

**Comment by Metinaltunsu7894** [comment]
Metin altunsu
