### ISSUE TITLE
generated an exception whilst handling plugin message (Bungeecord?)

### ISSUE THREAD

**Issue by SigGianni** [SergiFerry/PlayerNPC#38]
Log: https://mclo.gs/JnMGikU

**Comment by tomikcz987** [comment]
Same problem Purpur 1.19.4  with latest Waterfall

**Comment by RealKomander** [comment]
same issue, paper 1.20.1, latest velocity

```
[15:03:40 WARN]: [PlayerNPC] Plugin PlayerNPC v2023.6 generated an exception whilst handling plugin message
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletableFuture.complete(Object)" because the return value of "java.util.Map.get(Object)" is null
        at dev.sergiferry.playernpc.integration.integrations.BungeeCord$SubChannel$PlayerCount.listen(BungeeCord.java:402) ~[PlayerNPC (2).jar:?]
        at dev.sergiferry.playernpc.integration.integrations.BungeeCord.lambda$onPluginMessageReceived$0(BungeeCord.java:85) ~[PlayerNPC (2).jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at dev.sergiferry.playernpc.integration.integrations.BungeeCord.onPluginMessageReceived(BungeeCord.java:85) ~[PlayerNPC (2).jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3545) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-32]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-32]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-32]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-32]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-32]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

[latest.log](https://github.com/SergiFerry/PlayerNPC/files/12214853/latest.log)

**Comment by crokdiab** [comment]
Same, with Paper 1.20.1 and last build of waterfall

**Comment by SergiFerry** [comment]
add me discord @sergiferry and i will send you a beta version without that
error
