### ISSUE TITLE
Spam with Velocity server

### ISSUE THREAD

**Issue by VanyaNexus** [SergiFerry/PlayerNPC#42]
After starting the server with the Velocity proxy, the plugin spams the same error:

`[17:50:07] [Server thread/INFO]: PlayerNPC | Hooked into BungeeCord as msrv1_1 server
[17:50:07] [Server thread/WARN]: [PlayerNPC] Plugin PlayerNPC v2023.6 generated an exception whilst handling plugin message
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletableFuture.complete(Object)" because the return value of "java.util.Map.get(Object)" is null
	at dev.sergiferry.playernpc.integration.integrations.BungeeCord$SubChannel$PlayerCount.listen(BungeeCord.java:402) ~[PlayerNPC.jar:?]
	at dev.sergiferry.playernpc.integration.integrations.BungeeCord.lambda$onPluginMessageReceived$0(BungeeCord.java:85) ~[PlayerNPC.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at dev.sergiferry.playernpc.integration.integrations.BungeeCord.onPluginMessageReceived(BungeeCord.java:85) ~[PlayerNPC.jar:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3743) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1372) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:190) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1349) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1342) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1320) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:50:07] [Server thread/WARN]: [PlayerNPC] Plugin PlayerNPC v2023.6 generated an exception whilst handling plugin message
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletableFuture.complete(Object)" because the return value of "java.util.Map.get(Object)" is null
	at dev.sergiferry.playernpc.integration.integrations.BungeeCord$SubChannel$PlayerCount.listen(BungeeCord.java:402) ~[PlayerNPC.jar:?]
	at dev.sergiferry.playernpc.integration.integrations.BungeeCord.lambda$onPluginMessageReceived$0(BungeeCord.java:85) ~[PlayerNPC.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at dev.sergiferry.playernpc.integration.integrations.BungeeCord.onPluginMessageReceived(BungeeCord.java:85) ~[PlayerNPC.jar:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3743) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1372) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:190) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1349) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1342) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1320) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:git-MultiPaper-"40f3d1b"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by giopera** [comment]
Same on a Paper server connected to a Waterfall one
